package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Secao;

/**
 *
 * @author Win10 x64
 */
public class DialogPoltronas extends javax.swing.JDialog {

    private final int qtd;
    private JButton poltronas[];
    private JButton selecionada;
    private boolean apenasVisualizar;
    private Secao secao;

    private ArrayList<Integer> oucupadas;

    /**
     * Creates new form DiaologPoltronas
     */
    public DialogPoltronas(java.awt.Frame parent, boolean modal, boolean apenasVisualizar, Secao secao) {
        super(parent, modal);
        initComponents();

        this.apenasVisualizar = apenasVisualizar;
        this.secao = secao;
        qtd = this.secao.getSala().getQtdPoltronas();
        oucupadas = this.secao.getPoltronasOucupadas();

        poltronas = new JButton[qtd];
        selecionada = new JButton();

        configPoltronas();

        this.setLayout(new GridLayout(5, 5, 5, 3));
        this.setSize(new Dimension(480, 380));
        this.setResizable(false);
//        this.setPreferredSize(new Dimension(480, 380));
//        this.setMinimumSize(new Dimension(480, 380));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void configPoltronas() {
        for (int i = 0; i < qtd; i++) {
            poltronas[i] = new JButton("" + (i + 1));
            poltronas[i].setPreferredSize(new Dimension(45, 45));
            poltronas[i].setBackground(Color.red);

            if (oucupadas != null) {
                if (oucupadas.contains(i) || apenasVisualizar) {
                    if (oucupadas.contains(i)) {
                        poltronas[i].setBackground(Color.red);
                    }
                    
                    poltronas[i].setFocusPainted(false);
                } else if (!oucupadas.contains(i) || !apenasVisualizar) {
                    poltronas[i].addActionListener(listener);
                }
            }

            JPanel jp = new JPanel();
            jp.add(poltronas[i]);
            this.add(jp);
        }
    }

    ActionListener listener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
//            if (e.getSource() instanceof JButton) {
//                String text = ((JButton) e.getSource()).getText();
//                JOptionPane.showMessageDialog(null, text);
//            }
            selecionada.setBackground(Color.GRAY);
            selecionada = ((JButton) e.getSource());
            selecionada.setBackground(Color.GREEN);
        }
    };


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
